---
title: "Clase9"
author: "Victoria"
date: "6/27/2020"
output: html_document
---

```{r}
library(tidyverse)
library(dslabs)
#install.packages("dslabs")
# https://bradleyboehmke.github.io/HOML/kmeans.html
mnist <- dslabs::read_mnist()
```


```{r}
glimpse(mnist)
```


```{r}
features <- mnist$train$images
glimpse(features)
```

```{r}
labels <- mnist$train$labels
glimpse(labels)
# features %>%
#   as.data.frame()


# features$labels <- as.data.frame(labels)

```


```{r}
str(features[1,])
d <- matrix(features[1,], nrow=28, byrow = TRUE)
```


```{r}
library(reshape2)
digito <- melt(d)
digito
```

```{r}
theme_set(theme_light())
ggplot(digito, aes(x = Var1, y = Var2)) +
  geom_raster(aes(fill=value))
```

```{r}
library(patchwork)
p <- function(i){
    d <- matrix(features[i,], nrow = 28, byrow = TRUE)
    digito<-melt(d)
    ggplot(digito, aes(x = Var2, y = Var1)) +
    geom_raster(aes(fill=value)) +  coord_fixed() +
      scale_y_reverse()+
      theme_void() + theme(legend.position = "none")
  }
```


```{r}
p(1) + p(2) + p(3) + p(4) + p(5) + p(6)
```

```{r}
# x <- features[2,] %>% as.data.frame()
# for(i in 1:10) {
#   if(labels[i] == 0){
#     x <- rbind(x, features[i,] %>% as.data.frame())
#   }
# }
# x

mean_digit <- list()
numbers <- match(1:9,labels)
for (i in 1:length(numbers)) {
  print(numbers[i])
  hist(features[numbers[i],], title='Histogram of grey scale by numbers')
  mean_digit[i] <- mean(features[i,])
}


```


```{r}
mnist_clustering <- kmeans(features, centers = 10, nstart = 10)
```


```{r}
str(mnist_clustering)
```


```{r}
# Extract cluster centers
mnist_centers <- mnist_clustering$centers
glimpse(mnist_centers)
```

#Crear los 10 charts con los números 

```{r}
dc <- matrix(mnist_centers[1,], nrow=28, byrow = TRUE)
digitoc <- melt(dc)
ggplot(digitoc, aes(x= Var2, y= Var1))+
  geom_raster(aes(fill=value)) + coord_fixed() + scale_y_reverse() +
  theme_void() + theme(legend.position = 'none') 

```

```{r}
# Plot typical cluster digits
par(mfrow = c(2, 5), mar=c(0.5, 0.5, 0.5, 0.5))
layout(matrix(seq_len(nrow(mnist_centers)), 2, 5, byrow = FALSE))
for(i in seq_len(nrow(mnist_centers))) {
  image(matrix(mnist_centers[i, ], 28, 28)[, 28:1],xaxt="n", yaxt="n")
}
```

```{r}
# Create mode function
mode_fun <- function(x){  
  which.max(tabulate(x))
}

 

mnist_comparison <- data.frame(
  cluster = mnist_clustering$cluster,
  actual = mnist$train$labels
) %>%
  group_by(cluster) %>%
  mutate(mode = mode_fun(actual)) %>%
  ungroup() %>%
  mutate_all(factor, levels = 0:9)

 

# Create confusion matrix and plot results
yardstick::conf_mat(
  mnist_comparison, 
  truth = actual, 
  estimate = mode
) %>%
  autoplot(type = 'heatmap')
```

## Actividad K-means IRIS

```{r}
library(datasets)
head(iris)
```


```{r}
ggplot(iris, aes(Petal.Length, Petal.Width, color = Species)) + geom_point()
```

```{r}
set.seed(10)
kclust<- kmeans(iris$Petal.Length, centers = 3)
kclust
iris$predict <- kclust$cluster

# d<-data.frame(kclust$centers)
```


```{r}

p <- ggplot(iris) +
      # original plot
      geom_point(aes(x=Petal.Length, y=Petal.Width, color = Species, alpha= .5, size= 2)) +
      # predict plot
      geom_point(aes(x=Petal.Length, y=Petal.Width, shape = factor(predict)))

# ggplot(iris, aes(Petal.Length, Petal.Width, color = factor(predict))) + geom_point()
p

```

```{r}


# Create confusion matrix and plot results
yardstick::conf_mat(
  iris, 
  truth = Species, 
  estimate = mode
) %>%
  autoplot(type = 'heatmap')
```



